name: Front-end CI

on:
  workflow_dispatch:
  push:
      branches: [main]
  pull_request:
      branches: [main]

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Yarn Install
        run : yarn install

      - name: run cypress tests in chrome
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
            browser: chrome
            record: true
            build: yarn build:ci
            start: yarn start:ci
            wait-on: 'http://localhost:3000'
        env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}